### ISSUE TITLE
Speed up Eventcorrelator

### ISSUE THREAD

**Issue by reiserm** [reiserm/Xana#13]
Yuriy suggested to make changes to the eventcorrelator like in [this version](https://github.com/silx-kit/dynamix/blob/Yuriy/dynamix/correlator/event_y.py) to speed up the computation.

**Comment by RobertRosca** [comment]
I'm not too sure about the what all of the different correlators are called, is this about the multi-tau correlator I mentioned in this issue https://github.com/reiserm/midtools/issues/7?

**Comment by reiserm** [comment]
No, the eventcorrelator is different from the multi-tau correlator. I will add details to the documentation. We could at a later stage think about translating the correlators to Cython to speed-up the calculation.

**Comment by reiserm** [comment]
Solved in by c3d5c3f.
