### ISSUE TITLE
Replacing Fortran with Cython

### ISSUE THREAD

**Issue by RobertRosca** [reiserm/Xana#4]
PR #3 makes it so that numpy is a build-time dependency, allowing it to compile the fortran code during the install step.

Looked at the fortran code while doing this and I think we can replace it with python or cython without much performance loss, which would be nice. Spoke to @philsmt and he quickly wrote some cython code that could be used to replace the fortran:

```cython
# cython: boundscheck=False, wraparound=False, cdivision=True

from numpy cimport ndarray

def fecorrt3m(ndarray[int, ndim=1, mode='fortran'] pix,
              ndarray[int, ndim=1, mode='fortran'] t,
              ndarray[int, ndim=2, mode='fortran'] cc,
              int lpi, int nt):

    cdef int t0, i = 0, j = 0

    for i in range(lpi):
        t0 = t[i]
        j = i + 1

        while pix[j] == pix[i]:
            cc[t[j], t0] = cc[t[j], t0] + 1
            j += 1

            if j == lpi:
                break

        i += 1

    # Common math operation of some name.
    for i in range(nt - 1):
        for j in range(nt - 1):
            cc[j, i] = cc[j, i] + cc[i, j]
            cc[i, j] = cc[j, i]
```

Do you have a script that calls the `Xana.XpcsAna.fecorrt3m` method which we could use to test and benchmark this? It'd be nice to replace the fortran code as the f2py compilation step can still be a bit iffy depending on what compiler the user has available and (as you found out) what version of numpy they have. Doing it with cython instead should be more reliable.

**Comment by reiserm** [comment]
`Xana.XpcsAna.fecorrt3m` is used in the **event-correlator**. It is another method to calculate correlation functions and is used in the example notebook in the **Processing Data** section 

XPCS Eventcorrelator
d.analyze(-1, 'xpcs_evt', verbose=True, first=1,)

this could be used for testing.

There is actually another tool that is available as a Fortran routine. `Xana.Xdrop.dropimgood_sel`. I do not use it at the moment and it is not essential for `Xana`. 

What would be the advantage of cython over Fortran? Is it only convenience?

**Comment by reiserm** [comment]
We attack this issue in #6 and start by converting fecorrt3 to cython
